### ISSUE TITLE
should handle time as nanoseconds since specified time

### ISSUE THREAD

**Issue by dankelley** [dankelley/oceanglider#108]
I see that format in a netcdf file that I just got from @clayton33 via @richardsc, as below (from `ncdump -h` on the file).

At present, `oceglider` gives incorrect dates, because when it reads a netcdf file, it expects time to be floating-point seconds since 1970.  Well, that's if I recall correctly ... I need to find another file in the older netcdf format.  (Maybe I'll talk with Clark about this tomorrow.)

I'll make it handle both styles.  I guess I can look into the attributes for the `time` variable, to learn that.

Actually, the numbers seem a tad strange, but maybe that's okay.  (I'm used to seeing times in unix-style format, as seconds since 1970-01-01 00:00:00)

```
       int64 time(time) ;
                time:axis = "T" ;
                time:long_name = "time" ;
                time:source = "Timestamp" ;
                time:standard_name = "time" ;
                time:units = "nanoseconds since 2021-04-07 13:50:23.325086720" ;
                time:calendar = "proleptic_gregorian" ;
```

**Comment by dankelley** [comment]
Below is the code at the moment.  It's not even checking the origin time.  My bad.

https://github.com/dankelley/oceglider/blob/2af70a21f0acfe6f723fcb057a7b57495e9ea1a1/R/slocum_netcdf.R#L168

**Comment by dankelley** [comment]
Below is some simple code that could be a start.
```R

R version 4.4.0 (2024-04-24) -- "Puppy Cup"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin20

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(ncdf4)
> dir <- "~/Downloads/000-gliders/SEA021/M59/pyglider/L0-grid"
> file <- "dfo-Skye021-20210407_grid_delayed.nc"
> path <- paste0(dir, "/", file)
> o <- nc_open(path)
> timeUnitDescription <- ncatt_get(o, "time")$units
> timeUnitMeasure <- trimws(gsub("since.*", "", timeUnitDescription))
> # guess on timezone
> timeUnitSince <- as.POSIXct(trimws(gsub(".*since", "", timeUnitDescription)), tz = "UTC")
> timeUnitDescription
[1] "nanoseconds since 2021-04-07 13:50:23.325086720"
> timeUnitMeasure
[1] "nanoseconds"
> timeUnitSince
[1] "2021-04-07 13:50:23.325 UTC"
> 
```

**Comment by dankelley** [comment]
In an email, @richardsc said another file had as below. Luckily, that matches the pattern of the code in the prev comment.
```
 units: milliseconds since 1970-01-01T00:00:00+00:00
```

**Comment by dankelley** [comment]
Oh, hang on.  This fragment from Clark has a "T" in the string.  So the formats do not actually match.  And it has the +00:00 part to tell the timezone.  So I like that format more than the newer one.

**Comment by dankelley** [comment]
I have code that reads both formats now.

<details>

```R
library(ncdf4)

decodeTime <- function(s) {
    unit <- trimws(gsub("since.*", "", s))
    # handle choice of whether to separate HMS part with " " or "T"
    start <- gsub("T", " ", trimws(gsub(".*since", "", s)))
    add <- 0
    if (grepl("[+]", start)) {
        plus <- gsub(".*[+]", "", start)
        start <- gsub("[+].*", "", start)
        tmp <- strsplit(plus, ":")[[1]]
        hour <- as.numeric(tmp[1])
        min <- as.numeric(tmp[2])
        add <- hour * 3600 + min # seconds to add to result
    }
    list(unit = unit, start = as.POSIXct(start, tz = "UTC") + add)
}

dir <- "~/Downloads/000-gliders/SEA021/M59/pyglider/L0-grid"
file <- "dfo-Skye021-20210407_grid_delayed.nc"
path <- paste0(dir, "/", file)
o <- nc_open(path)
u <- ncatt_get(o, "time")$units
nc_close(o)
cat(u, "\n")
print(decodeTime(u))

# CR's case
u <- "units: milliseconds since 1970-01-01T00:00:00+00:00"
cat(u, "\n")
print(decodeTime(u))

# As CR's case but different timezone
u <- "units: milliseconds since 1970-01-01T00:00:00+01:00"
cat(u, "\n")
print(decodeTime(u))
```

creates

```
nanoseconds since 2021-04-07 13:50:23.325086720 
$unit
[1] "nanoseconds"

$start
[1] "2021-04-07 13:50:23.325 UTC"

units: milliseconds since 1970-01-01T00:00:00+00:00 
$unit
[1] "units: milliseconds"

$start
[1] "1970-01-01 UTC"

units: milliseconds since 1970-01-01T00:00:00+01:00 
$unit
[1] "units: milliseconds"

$start
[1] "1970-01-01 01:00:00 UTC"
```

**Comment by dankelley** [comment]
I'm not sure if this is still relevant, since the file format was in-development before.  Is this still a relevant topic, @clayton33 and @richardsc?

**Comment by clayton33** [comment]
If using C-PROOF files as your test files, you might still find some that have various time units. Going forward they should all be `"seconds since ..".`. So... I'm not sure, perhaps it's still relevant ?

**Comment by richardsc** [comment]
I _think_ that this isn't an issue, as it was only something that came up in the preliminary files that @clayton33 was generating, but it is possible that some of the other CPROOF files might have it. That being said, if there are other files that contain nanosecond time, the best solution is likely to re-process them (at the source) rather than adapt the package ... there are no clocks on gliders that are actually accurate to 10^-9 seconds ...

**Comment by dankelley** [comment]
Thanks, @richardsc ... I'll close now.
