### ISSUE TITLE
read.glider.seaexplorere.delayed() docs for removeTimeSincePowerOn need more detail

### ISSUE THREAD

**Issue by dankelley** [dankelley/oceanglider#109]
It doesn't state the unit.  And, frankly, I think the docs should suggest using 5 minutes or so.  Maybe it should even default to that.  I say this because of the stuff in the attached zipfile.  (This is some stuff that can go into a revamp of the package. I'm using a west-coast server that was pointed out by @clayton33 yesterday.  This solves the problem of finding suitable test files that are up-to-date and checkable by users without knowing obscure ftp addresses.)

Thoughts by @richardsc and @clayton33 welcomed, of course.

PS. the bad data last longer than I thought they normally did.  And the behavour does not look like a running-average thing.  Notice that SA is crazily low and then quickly jumps high.  Oh well, I guess I don't really care why this happens -- that's for Sea Explorer to worry about.  Users just want to know how to get some data that are representative of the ocean.
[starting_problem.zip](https://github.com/user-attachments/files/16798952/starting_problem.zip)

**Comment by dankelley** [comment]
This is the spot in the code that handles this.  I think this means that the unit of `removeTimeSincePowerOn` is an estimate of inter-sample times, not say seconds or minutes.  

https://github.com/dankelley/oceglider/blob/172a66fa73aa111d0f5dfca267aa459ff0662771/R/seaexplorer_delayed.R#L354

**Comment by clayton33** [comment]
I was just looking at this function. I'm not sure if SeaExplorers have changed this behaviour (i.e. it doesn't start logging data until the `warmUp` period has passed). But I do know that a `warmUp` time is set for each instrument in a configuration file prior to the mission. 

Related/unrelated. I'm comparing processed data with the raw data as I suspect that there's something funny going on when the `gli.sub` data is matched up with the `pld1.raw` data by a processing toolbox. Anyways... we might want to re-think this function a bit, as right now it doesn't do what I want, which I think is the most basic thing - look at the raw data (not just the raw science data) ! I have ideas ...

**Comment by dankelley** [comment]
Hm, I need to read that code more closely.  In "develop" commit 527d61f40259baf0e0928c73fcb707dace66f1c2, I created `sandbox/dk/03_start_chop` to do some tests (including of downloading these west-coast files ... that will be for vignettes and tests, too).

Attached is what I get from `03_chop_early.R` in that directory.

The left panel is all the data (for this first few files).  The middle is after I played with the skipping parameter.  And the right is a test in which I find anomalous sigma0 and SA values (really, these are quite correlated for this type of error).

Note that a value of `removeTimeSincePowerOn` equal to 18000 is giving a 1.33 h skip.  I don't think I understand that code, and so I'm not clear on how to reword the docs on this parameter.  

Some points to discuss:

1. Wouldn't it be easier to express this in terms of time units, say seconds?

2. Is my quantile-based method useful at all, even as a hint?  This is basically what my eye is doing: looking for points near the start that don't look like later points.  The S tends to be the most distinct, but in my little test I also did density because that's really the most physical thing (in terms of forces).




![03_chop_early](https://github.com/user-attachments/assets/8f66df69-95f4-405d-bae7-561f105113a4)

**Comment by clayton33** [comment]
1. If this parameter is retained +1.0 vote for representing it as time unit, seconds makes sense.
2. I haven't looked closely at the code, but does `removeTimeSincePowerOn` remove x number of seconds from each profile ? Or just from the first profile ?

**Comment by dankelley** [comment]
Oh, I had a look at the code and the reason this happens is that, in the code below, `dt` is computed as the median difference between times when there are good temperature data. But that's hard for the user to know, without some detailed examination.  (For this particular test case, only about 1 in 4 temperatures are non-NA, so the required value of `removeTimeSincePowerOn` is 18000.  But divide 18000/4 and you get 4500 seconds, or 1.24 hours.  And *that* number makes sense from what you see if you plot the data.

Therefore I am going to change this, to compute `dt` based on time, and not time-of-good-temperature.  That will be a breaking change for old code, but we are talking about making `oceglider` have a higher visibility, and so I'm doing this to help other users.

Of course I'll document the change.  I will also be making a vignette for sea-explorer, and will explain there (with these data) how to get an idea for that value by graphing, and also how to get it with quantile computers.

I'll do the code fix right now.  The vignette won't be for a while.  I want to get more materials ready for that, so I can just write a first draft in one go.  I've found that writing a vignette a bit at a time (like writing a paper a bit at a time) leads to awkward text and a lot of wasted effort.

```r
            dt <- median(diff(as.numeric(df$time[!is.na(df$temperature)])))
            ok <- rep(TRUE, length(df$time))
            n <- round(removeTimeSincePowerOn / dt)
            for (s in starts) ok[s:(s + n)] <- FALSE
            df <- df[ok, ]
 ```

**Comment by dankelley** [comment]
Oh, this was done yesterday or the day before, and I forgot to close the issue.  Since I was the reporter, I won't bother giving commit hash code etc.
