### ISSUE TITLE
are units in the DFO sample IOOS file actually radians?

### ISSUE THREAD

**Issue by dankelley** [dankelley/oceanglider#94]
@clayton33 I looked inside the netcdf file and it is stating the units for pitch etc to be radians.  I wonder if something is wrong in the code that created that netcdf file? When I do as below, I get a histogram that suggests the unit must be degrees.

PS. this is not an issue for the `oceanglider` package, but I didn't know where else to report it.  I don't think `oceanglider` should refuse to accept the unit that is in the netcdf file, but I sort of think it ought to give a warning if the file says radians and the numbers are of order -20 or +20.  With such a warning, folks could work with old, broken, files.  But, of course, perhaps this file is so new and so private that we don't need to worry about normal users ever seeing such a file.  Up to @clayton33 to decide, I reckon.
```R
library(oceanglider)
d<-read.glider.netcdf.ioos("sandbox/cl/02testDFO/dfo-mersey022-20220907.nc")
hist(d[["pitch"]],breaks=100)
```
<img width="567" alt="Screenshot 2022-11-26 at 9 38 48 AM" src="https://user-images.githubusercontent.com/99469/204091748-d94604bc-8b14-4f56-bcb2-fe35b417c57f.png">

**Comment by clayton33** [comment]
Thanks, I'll have a look at where this issue stems from.

**Comment by richardsc** [comment]
They're definitely not radians, but degrees (at least as measured in the raw file). This is maybe just a metadata (i.e. `deployment.yml`) configuration thing?

**Comment by clayton33** [comment]
Issue found, come from when the netcdf file is created. It is in fact `degrees`, not `radians`, as confirmed by the data and the manual from Alseamar.  This has been noted for future processing of our data. I re-processed the data and put it in the `develop` branch.
